# Pre-commit Quality Gates Configuration
# This file defines quality gates that run before commits are allowed

repos:
  - repo: local
    hooks:
      - id: quality-gates
        name: Quality Gates
        entry: uv run python scripts/quality_gates.py
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        verbose: true
