version: '3'

tasks:
  setup:
    desc: Setup Bazel build system
    cmds:
      - echo "Bazel build system is ready"

  test:
    desc: Run test suite with Bazel
    cmds:
      - bazel test //...

  run:
    desc: Run the simulator
    cmds:
      - bazel run //src/traffic_sim:traffic_sim_bin

  lint:
    desc: Run linting with Bazel
    cmds:
      - bazel build //...

  format:
    desc: Format code with Bazel
    cmds:
      - bazel build //...

  precommit:install:
    desc: Pre-commit hooks are deprecated in favor of Bazel
    cmds:
      - echo "Pre-commit hooks are deprecated. Use 'bazel build //...' for quality checks."

  precommit:run:
    desc: Pre-commit hooks are deprecated in favor of Bazel
    cmds:
      - echo "Pre-commit hooks are deprecated. Use 'bazel build //...' for quality checks."

  quality:
    desc: Run quality analysis with Bazel
    cmds:
      - bazel build //...

  quality:monitor:
    desc: Run detailed quality monitoring with Bazel
    cmds:
      - bazel test //... --test_output=all

  quality:analyze:
    desc: Run comprehensive static analysis with Bazel
    cmds:
      - bazel query //...

  performance:
    desc: Run performance benchmark
    cmds:
      - bazel run //scripts:benchmarking_framework -- --mode=benchmark

  performance:scale:
    desc: Run scale performance testing
    cmds:
      - bazel run //scripts:benchmarking_framework -- --mode=scale

  performance:monitor:
    desc: Run real-time performance monitoring
    cmds:
      - bazel run //scripts:benchmarking_framework -- --mode=monitor

  profile:
    desc: Run simulation profiling
    cmds:
      - bazel run //scripts:benchmarking_framework -- --mode=profile

  validate:
    desc: Run validation tests
    cmds:
      - bazel test //tests:validation_test

  clean:
    desc: Clean all temporary files and caches from the project
    cmds:
      - bazel clean
      - find . -name "*.pyc" -delete
      - find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name ".pytest_cache" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name ".hypothesis" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name ".pyright_cache" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name ".ruff_cache" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name "*.log" -delete
      - find . -name ".coverage*" -delete
      - find . -name "htmlcov" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name ".DS_Store" -delete
      - find . -name "*.tmp" -delete
      - find . -name "*.temp" -delete
      - echo "Cleaned all temporary files and caches"
