version: '3'

tasks:
  setup:
    desc: Create/refresh environment with uv and install dev deps
    cmds:
      - uv sync --extra dev

  test:
    desc: Run test suite with coverage
    cmds:
      - uv run python -m pytest --cov=traffic_sim --cov-report=term-missing

  run:
    desc: Run the simulator
    cmds:
      - uv run python -m traffic_sim

  lint:
    desc: Run ruff
    cmds:
      - uv run ruff check src tests

  format:
    desc: Run black in check mode (remove --check to autoformat)
    cmds:
      - uv run black --check src tests

  precommit:install:
    desc: Install pre-commit hooks
    cmds:
      - uv run pre-commit install

  precommit:run:
    desc: Run pre-commit on all files
    cmds:
      - uv run pre-commit run --all-files

  clean:
    desc: Clean all temporary files and caches from the project
    cmds:
      - find . -name "*.pyc" -delete
      - find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name ".pytest_cache" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name ".hypothesis" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name ".mypy_cache" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name ".ruff_cache" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name "*.log" -delete
      - find . -name ".coverage*" -delete
      - find . -name "htmlcov" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name ".DS_Store" -delete
      - find . -name "*.tmp" -delete
      - find . -name "*.temp" -delete
      - echo "Cleaned all temporary files and caches"
