# Quality Gates Configuration for Traffic Simulator
# Defines thresholds and rules for code quality enforcement

# Overall Quality Gates
overall:
  max_critical_issues: 0
  max_high_issues: 0
  max_medium_issues: 5
  max_low_issues: 10
  max_total_issues: 15

# Tool-specific Quality Gates
tools:
  ruff:
    max_errors: 0
    max_warnings: 5
    max_info: 10
    fail_on_format_issues: true

  pyright:
    max_errors: 0
    max_warnings: 3
    fail_on_any_error: true

  bandit:
    max_high_severity: 0
    max_medium_severity: 0
    max_low_severity: 3

  radon:
    max_complexity_C: 0  # No C complexity functions
    max_complexity_D: 0  # No D complexity functions
    max_complexity_E: 0  # No E complexity functions
    max_complexity_F: 0  # No F complexity functions
    average_complexity_max: 3.0

# Coverage Requirements
coverage:
  min_line_coverage: 70
  min_branch_coverage: 60
  min_function_coverage: 75

# Performance Requirements
performance:
  max_cyclomatic_complexity: 10
  max_cognitive_complexity: 15
  max_function_length: 50
  max_class_length: 200

# Security Requirements
security:
  max_security_issues: 0
  require_security_scan: true
  fail_on_high_severity: true
  fail_on_medium_severity: true

# Documentation Requirements
documentation:
  require_docstrings: true  # Enable for production
  min_docstring_coverage: 80  # Set to 80 for production
  require_type_hints: true
  require_markdown_validation: true
  require_link_validation: true
  require_spell_check: true

# Rules Requirements
rules:
  require_frontmatter: true
  max_global_rules: 5
  require_globs: true
  require_description: true
  require_alwaysApply: true
  require_unique_globs: true
  max_token_count: 900

# Enforcement Success Metrics
enforcement_metrics:
  commit_message_compliance: 100  # Percentage of commits following conventional format
  documentation_validation_pass: 100  # Percentage of docs passing validation
  rules_validation_pass: 100  # Percentage of rules passing validation
  pre_commit_hooks_pass: 100  # Percentage of pre-commit hooks passing
  quality_gates_pass: 100  # Percentage of quality gates passing

  # Enforcement targets
  targets:
    commit_message_compliance: 95  # Minimum 95% compliance
    documentation_validation_pass: 95  # Minimum 95% validation pass rate
    rules_validation_pass: 95  # Minimum 95% validation pass rate
    pre_commit_hooks_pass: 95  # Minimum 95% hook pass rate
    quality_gates_pass: 95  # Minimum 95% quality gates pass rate
