#!/usr/bin/env python3
"""
Ensure runs directory structure exists.

This script creates the runs directory structure if it doesn't exist,
ensuring all profiling and benchmark output has a proper place to be saved.
"""

from pathlib import Path


def ensure_runs_directory():
    """Create the runs directory structure if it doesn't exist."""
    runs_dir = Path("runs")

    # Create main runs directory
    runs_dir.mkdir(exist_ok=True)

    # Create subdirectories
    subdirs = ["profiling", "benchmarks", "performance", "scaling"]

    for subdir in subdirs:
        (runs_dir / subdir).mkdir(exist_ok=True)

    # Create README if it doesn't exist
    readme_path = runs_dir / "README.md"
    if not readme_path.exists():
        readme_content = """# Runs Directory

This directory contains all profiling, benchmarking, and performance analysis output files generated by the traffic simulation project.

## Directory Structure

```
runs/
├── README.md                 # This file
├── profiling/               # Profiling analysis outputs
├── benchmarks/              # Benchmark results
├── performance/             # Performance analysis outputs
└── scaling/                 # Scaling analysis outputs
```

## Usage

All profiling and benchmarking scripts automatically save their output to this directory. The directory structure is organized by analysis type.

## Git Ignore

This entire directory is ignored by git to prevent committing large data files and generated outputs.
"""
        readme_path.write_text(readme_content)

    print("✓ Runs directory structure ensured")
    print(f"  Created: {runs_dir.absolute()}")
    for subdir in subdirs:
        print(f"  Created: {runs_dir / subdir}")


if __name__ == "__main__":
    ensure_runs_directory()
