name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Sync env
        run: uv sync --extra dev
      - name: Run quality gates
        run: |
          uv run python scripts/quality_gates.py
      - name: Run tests with coverage
        run: uv run pytest --cov=traffic_sim --cov-report=term-missing -q
