name: Profile Simulation

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          pip install uv

      - name: Sync dependencies
        run: |
          uv sync --extra dev

      - name: Run profiling script
        run: |
          uv run python scripts/profile_simulation.py --steps 500 --dt 0.02 --csv profiling_stats.csv --cprofile

      - name: Upload profiling CSV
        uses: actions/upload-artifact@v4
        with:
          name: profiling-stats
          path: profiling_stats.csv
